version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
